Repository Bellman-devs/bellman, pull requests merged in 2021-04, with the labels that each got.

#19 Release/0.1.0
  .github/workflows/publish-docs.yml
  .github/workflows/upload-pypi.yaml
  README.md
  docs/conf.py
Labels: release

#22 manual action triggers
  .github/workflows/build-and-test.yml
  .github/workflows/publish-docs.yml
  .github/workflows/slow-tests.yml
  .github/workflows/upload-pypi.yaml
Labels: enhancement

#23 John/fix none loss in harness
  bellman/training/schedule.py
  tests/unit/bellman/training/test_schedule.py
Labels: bug
